import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {IDBFactory,IDBKeyRange} from 'fake-indexeddb';
import {History,blank,mergeMemos} from '../js/model.js';
import {validateBackup,decodeBackup,combineBackup} from '../js/backup.js';
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'https://yuuuh26.github.io/flash-memo/',pretendToBeVisual:true});
const w=dom.window;globalThis.window=w;globalThis.document=w.document;globalThis.indexedDB=new IDBFactory();globalThis.IDBKeyRange=IDBKeyRange;Object.defineProperty(globalThis,'navigator',{value:w.navigator,configurable:true});
w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
globalThis.FileReader=class{readAsDataURL(blob){blob.arrayBuffer().then(buffer=>{this.result=`data:${blob.type};base64,${Buffer.from(buffer).toString('base64')}`;this.onload();}).catch(error=>{this.error=error;this.onerror();});}};
w.HTMLAnchorElement.prototype.click=function(){downloads.push(this.download);};const downloads=[];
Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>{copied=value;}}});let copied;
const $=id=>document.getElementById(id);const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,label='state'){for(let i=0;i<500;i++){if(await fn())return;await sleep(10);}throw new Error('Timeout: '+label+' | '+$('status').textContent+' | '+$('toast').textContent);}
const report=[];const passed=name=>{report.push(name);console.log('PASS',name);};
await import('../js/app.js');const db=await import('../js/db.js');await wait(()=>$('status').textContent==='入力すると自動保存','startup');
async function snapshot(){return db.readSnapshot();}
async function view(name){document.querySelector(`[data-view="${name}"]`).click();await wait(()=>!$(name).hidden,'view '+name);}
function type(value){$('body').value=value;$('body').dispatchEvent(new w.Event('input',{bubbles:true}));}
async function save(){await wait(()=>$('status').textContent==='保存済み','autosave');await sleep(20);}
async function next(){const id=$('body').value;$('next').click();await wait(()=>$('body').value===''&&!$('next').disabled,'next '+id);}
async function addTag(name){$('newTag').value=name;$('newTagForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>$('newTag').value==='','add tag');}
passed('起動・IndexedDBストア作成');
await next();assert.equal((await snapshot()).memos.length,0);passed('空メモの連続作成防止');
await view('settings');await addTag('仕事');await addTag('アイデア');await view('write');
$('quickTags').querySelector('button').click();type('最初の走り書き');await save();let s=await snapshot();assert.equal(s.memos[0].body,'最初の走り書き');assert.equal(s.memos[0].tagIds.length,1);passed('400ms自動保存・成功状態・固定タグID');
$('quickTags').querySelectorAll('button')[1].click();assert.equal($('body').value,'最初の走り書き');await save();assert.equal((await snapshot()).memos[0].tagIds.length,2);passed('タグ変更時の本文保持・複数タグ');
await next();assert.equal(document.activeElement,$('body'));assert.equal($('quickTags').querySelectorAll('.selected').length,2);type('二つ目');await save();await next();passed('次のメモ・フォーカス・クイックタグ引き継ぎ');
const long='長文テスト🌸\n'.repeat(8000);type(long);await save();assert.equal((await snapshot()).memos.find(m=>m.body===long).body.length,long.length);passed('長文64000文字以上の保存');
type('変更前');await save();type('変更後');$('undo').click();assert.equal($('body').value,'変更前');$('redo').click();assert.equal($('body').value,'変更後');await save();passed('本文Undo・Redo');
$('quickTags').querySelector('button').click();$('undo').click();assert.equal($('quickTags').querySelectorAll('.selected').length,2);await save();passed('タグUndo');
$('copyCurrent').click();await wait(()=>copied==='変更後');await view('list');document.querySelector('.memo-actions button').click();await wait(()=>copied);passed('入力画面・一覧から本文コピー');
$('search').value='走り書き';$('search').dispatchEvent(new w.Event('input'));assert.equal(document.querySelectorAll('.memo-card').length,1);$('search').value='アイデア';$('search').dispatchEvent(new w.Event('input'));assert.equal(document.querySelectorAll('.memo-card').length,3);$('search').value='';$('search').dispatchEvent(new w.Event('input'));passed('本文・タグ名の端末内検索');
$('selectMode').click();document.querySelectorAll('.memo-open')[0].click();document.querySelectorAll('.memo-open')[1].click();assert.equal(document.querySelectorAll('.chosen').length,2);$('bulkMerge').click();await wait(()=>$('mergePreview'));assert.match($('mergePreview').value,/────────/);assert.equal($('moveOriginals').checked,false);$('commitMerge').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).memos.length,4);assert.equal((await snapshot()).memos.filter(m=>m.deletedAt).length,0);assert.equal((await snapshot()).memos.find(m=>m.mergedAt).mergedFromIds.length,2);passed('複数選択・マージプレビュー・元メモ保持');
$('selectMode').click();const before=(await snapshot()).memos.length;document.querySelector('.memo-actions .danger').click();await wait(()=>$('dialog').open&&$('confirmAction'));$('confirmAction').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).memos.filter(m=>m.deletedAt).length,1);await view('settings');document.querySelector('.trash-row button').click();await wait(async()=>!(await snapshot()).memos.some(m=>m.deletedAt));assert.equal((await snapshot()).memos.length,before);passed('削除・ゴミ箱復元');
// Rename a tag while keeping IDs; batch quick-tag edits and order changes.
const tagId=(await snapshot()).tags[0].id;document.querySelector('.tag-actions button').click();await wait(()=>$('tagName'));$('tagName').value='仕事用';$('saveTagName').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).tags[0].id,tagId);assert.ok((await snapshot()).memos.some(m=>m.tagIds.includes(tagId)));passed('タグ名前変更でもメモ関連を維持');
for(const checkbox of document.querySelectorAll('#tagManagement input')){checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change'));}$('quickRemove').click();await wait(async()=>!(await snapshot()).tags.some(t=>t.quick));$('quickAdd').click();await wait(async()=>(await snapshot()).tags.every(t=>t.quick));passed('複数タグをクイックへ一括追加・解除');
await view('write');await next();
// Image attachment via an actual Blob and DB roundtrip.
const blob=new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2FEAAAAASUVORK5CYII=','base64')],{type:'image/png'});blob.name='test.png';Object.defineProperty($('imageInput'),'files',{value:[blob],configurable:true});$('imageInput').dispatchEvent(new w.Event('change'));await wait(async()=>(await snapshot()).attachments.length===1);await wait(()=>document.querySelector('.image-tile'));await save();assert.equal((await snapshot()).attachments[0].blob.size,blob.size);await next();passed('画像添付・Blob保存・サムネイル・画像だけのメモ');
await view('settings');$('export').click();await wait(()=>$('confirmBackup'));assert.match($('exportResult').textContent,/ダウンロードを開始/);assert.match(downloads.at(-1),/flash-memo-backup_\d{4}-\d{2}-\d{2}_\d{4}\.json/);assert.equal((await snapshot()).backupState[0].confirmedCount,0);$('confirmBackup').click();await wait(()=>$('exportResult').textContent==='✓ バックアップ確認済み');const baseline=(await snapshot()).backupState[0].createdCount;passed('画像を含む完全エクスポート・ダウンロード表示・ユーザー確認カウント');
await view('write');for(let i=0;i<15;i++){type('連続メモ '+i);await next();}await wait(()=>!$('reminder').hidden);s=await snapshot();assert.equal(s.backupState[0].createdCount-baseline,15);$('backupLater').click();await wait(()=>$('reminder').hidden);passed('15件新規作成後の控えめな通知');
// Validate and decode a backup; orphan undo images are excluded just as in app export.
const {exportData}=await import('../js/backup.js');s=await snapshot();const references=new Set(s.memos.flatMap(m=>m.attachmentIds));s.attachments=s.attachments.filter(a=>references.has(a.id));s.settings=s.settings.map(c=>({...c,activeDraftId:s.memos.some(m=>m.id===c.activeDraftId)?c.activeDraftId:null}));const backup=await exportData(s);assert.equal(validateBackup(backup),backup);const decoded=decodeBackup(backup);assert.equal(decoded.attachments[0].blob.size,blob.size);passed('JSON検証・Base64画像復元');
assert.equal(combineBackup(s,decoded).memos.length,s.memos.length);const corrupt=structuredClone(backup);corrupt.memos[0].tagIds.push('missing');assert.throws(()=>validateBackup(corrupt));const badDate=structuredClone(backup);badDate.memos[0].createdAt='bad';assert.throws(()=>validateBackup(badDate));const badImage=structuredClone(backup);badImage.attachments[0].dataUrl='data:image/png;base64,%%%';assert.throws(()=>decodeBackup(badImage));passed('同一IDの重複防止・不正参照/日時/画像の拒否');
await view('settings');const countBefore=(await snapshot()).memos.length;Object.defineProperty($('importInput'),'files',{value:[{text:async()=>'{broken'}],configurable:true});$('importInput').dispatchEvent(new w.Event('change'));await wait(()=>$('importResult').textContent.includes('インポート失敗'));assert.equal((await snapshot()).memos.length,countBefore);passed('不正JSONのUI読み込みで既存データ不変');
Object.defineProperty($('importInput'),'files',{value:[{text:async()=>JSON.stringify(backup)}],configurable:true});$('importInput').dispatchEvent(new w.Event('change'));await wait(()=>$('commitImport'));$('commitImport').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).memos.length,countBefore);passed('追加・統合インポートのUI実行');
$('importMode').value='replace';Object.defineProperty($('importInput'),'files',{value:[{text:async()=>JSON.stringify(backup)}],configurable:true});$('importInput').dispatchEvent(new w.Event('change'));await wait(()=>$('beforeBackup'));assert.equal($('commitImport').disabled,true);$('beforeBackup').click();await wait(()=>downloads.at(-1).startsWith('flash-memo-before-import'));$('beforeConfirm').checked=true;$('beforeConfirm').dispatchEvent(new w.Event('change'));assert.equal($('commitImport').disabled,false);$('commitImport').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).attachments[0].blob.size,blob.size);passed('全置換・置換前バックアップ確認・画像復元');
// Image deletion confirmation and explicit history restoration.
await view('list');$('search').value='';$('search').dispatchEvent(new w.Event('input'));const imageTitle='画像メモ';const imageButton=[...document.querySelectorAll('.memo-open')].find(b=>b.textContent.includes(imageTitle));imageButton.click();await wait(()=>!$('write').hidden&&document.querySelector('.image-tile'));document.querySelector('.image-tile button').click();await wait(()=>$('dialog').open&&$('confirmAction'));assert.equal(document.querySelectorAll('.image-tile').length,1);$('confirmAction').click();await wait(()=>!$('dialog').open);assert.equal(document.querySelectorAll('.image-tile').length,0);$('undo').click();assert.equal(document.querySelectorAll('.image-tile').length,1);await save();passed('画像削除の確認・Undoによる復元');
// Batch note tags, tag ordering, and tag removal must keep all bodies intact.
await view('list');$('selectMode').click();document.querySelectorAll('.memo-open')[0].click();document.querySelectorAll('.memo-open')[1].click();$('bulkTags').click();await wait(()=>$('tagOperation'));$('tagOperation').value='remove';$('tagChoices').querySelector('button').click();$('applyTags').click();await wait(()=>!$('dialog').open);const selectedIds=[...document.querySelectorAll('.chosen .memo-open')].map(b=>b.textContent);assert.equal(selectedIds.length,2);passed('複数メモのタグ一括削除');
await view('settings');const originalOrder=(await snapshot()).tags.sort((a,b)=>a.order-b.order).map(t=>t.id);document.querySelectorAll('.tag-actions')[0].querySelectorAll('button')[3].click();await wait(async()=>(await snapshot()).tags.sort((a,b)=>a.order-b.order)[0].id!==originalOrder[0]);passed('タグの並び替え');
const bodiesBefore=(await snapshot()).memos.map(m=>m.body).sort();for(const checkbox of document.querySelectorAll('#tagManagement input')){checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change'));}$('deleteTags').click();await wait(()=>$('dialog').open&&$('confirmAction'));$('confirmAction').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).tags.length,0);assert.deepEqual((await snapshot()).memos.map(m=>m.body).sort(),bodiesBefore);assert.ok((await snapshot()).memos.every(m=>!m.tagIds.length));passed('複数タグ削除でも本文・画像を保持');
await view('list');$('selectMode').click();document.querySelector('.memo-actions .danger').click();await wait(()=>$('dialog').open&&$('confirmAction'));$('confirmAction').click();await wait(()=>!$('dialog').open);await view('settings');document.querySelectorAll('.trash-row button')[1].click();await wait(()=>$('dialog').open&&$('confirmAction'));const totalBefore=(await snapshot()).memos.length;$('confirmAction').click();await wait(()=>!$('dialog').open);assert.equal((await snapshot()).memos.length,totalBefore-1);passed('ゴミ箱内の確認付き完全削除');

// Transaction failure must roll back a clear and earlier puts.
const stable=await snapshot();await assert.rejects(db.write({memos:[stable.memos[0],{body:'missing ID'}]},true));assert.deepEqual(await snapshot(),stable);passed('トランザクション失敗時の全置換ロールバック');
const hist=new History({body:''});for(let i=0;i<80;i++)hist.push({body:String(i)});assert.equal(hist.items.length,51);hist.undo();hist.push({body:'branch'});assert.equal(hist.index,hist.items.length-1);passed('50段階Undo履歴・編集後Redo分岐');
const manifest=JSON.parse(await readFile(new URL('../manifest.webmanifest',import.meta.url),'utf8'));for(const key of ['id','start_url','scope'])assert.equal(manifest[key],'/flash-memo/');assert.ok(manifest.icons.some(i=>i.purpose==='maskable'));assert.match(html,/noindex/);const sw=await readFile(new URL('../sw.js',import.meta.url),'utf8');assert.match(sw,/flash-memo-shell-/);assert.doesNotMatch(sw,/indexedDB\.deleteDatabase/);passed('専用PWA識別子・maskable定義・noindex・DB非削除');
await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});await writeFile(new URL('../test-results/results.json',import.meta.url),JSON.stringify({at:new Date().toISOString(),checks:report,limitations:['実ブラウザの表示とService Workerオフライン挙動','Android実機のキーボード・PWAインストール・アイコン形状']},null,2));
console.log(`${report.length} checks passed.`);w.close();process.exit(0);
